objects/Application_Log__c.object
<CustomObject>
    <description>Application Logging Object</description>
    <fields>
        <fullName>Debug_Level__c</fullName>
        <label>Debug Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Debug</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Info</fullName>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Integration_Payload__c</fullName>
        <description>If log is integration related show payload</description>
        <inlineHelpText>If log is integration related show payload</inlineHelpText>
        <label>Integration Payload</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>Message to log</description>
        <inlineHelpText>Message to log</inlineHelpText>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Source_Function__c</fullName>
        <description>The originating function in the class (e.g. UpdateDivision() )</description>
        <inlineHelpText>The originating function in the class (e.g. UpdateDivision() )</inlineHelpText>
        <label>Source Function</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>The originating class (e.g. CustomerManagement)</description>
        <inlineHelpText>The originating class (e.g. CustomerManagement)</inlineHelpText>
        <label>Source</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <description>Raw exception stack trace for unhandled errors</description>
        <inlineHelpText>Raw exception stack trace for unhandled errors</inlineHelpText>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Timer__c</fullName>
        <description>The time in milliseconds for the transaction (e.g. For integration/batch apex messages it might be the time taken to process)</description>
        <inlineHelpText>The time in milliseconds for the transaction (e.g. For integration/batch apex messages it might be the time taken to process)</inlineHelpText>
        <label>Timer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Application Log</label>
    <nameField>
        <label>Application Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ApplicationLogUtility.cls
/*------------------------------------------------------------
    Author: Stefano Pramparo
    Company: Sky DE
    Description: A utility class for logging functionality, use the flush to store log on DB
    Inputs: n.a.
    Test Class: ApplicationLogUtility_Test
    
    History
    <Date>		<Authors Name> 		<Brief Description of Change>
    31.08.2018	Stefano Pramoaro 	Initial creation
------------------------------------------------------------*/
public class ApplicationLogUtility { 
        private static final Integer DMLHEAP =100;
        @TestVisible 
        private static List<Application_Log__c> logList;
        
        static{
            logList = new List<Application_Log__c>();
        }
        
        /*------------------------------------------------------------ 
    Author: Stefano Pramparo 
    Company: Sky DE
    Description: Function to log error message and flush immediatly
    Inputs: - logLevel: mandatory, values are Error,Warning, Info, Debug
    - sourceClass: object, class, flow, etc. generating error
    - sourceFunction: function name
    - logMessage: message to log
    - payLoad: payload for integration
    - ex: exception
    - timeTaken: execution time 
    Returns: n.a.
    History 
    <Date>	 		<Authors Name>		<Brief Description of Change> 
    31.08.2018		Stefano Pramparo	Created
    ------------------------------------------------------------*/
        public static void logMessageSync(String logLevel,String sourceClass, String sourceFunction,
                                          String logMessage,String payLoad,Exception ex,Long timeTaken){
                                              logMessage(logLevel,sourceClass, sourceFunction,logMessage, payLoad, ex, timeTaken);
                                              flush();
                                          }
        /*------------------------------------------------------------ 
    Author: Stefano Pramparo 
    Company: Sky DE
    Description: Function to add the error message in the lit; data is committed invoking flush method
    or when getLimitDmlRows()-1 has been reached
    Inputs: - logLevel: mandatory, values are Error,Warning, Info, Debug
    - sourceClass: object, class, flow, etc. generating error
    - sourceFunction: function name
    - logMessage: message to log
    - payLoad: payload for integration
    - ex: exception
    - timeTaken: execution time 
    Returns: n.a.
    History 
    <Date>	 		<Authors Name>		<Brief Description of Change> 
    31.08.2018		Stefano Pramparo	Created
    ------------------------------------------------------------*/
        public static void logMessage(String logLevel,String sourceClass, String sourceFunction,
                                      String logMessage,String payLoad,Exception ex,Long timeTaken){
                                          Application_Log__c log = new Application_Log__c(
                                              Debug_Level__c=logLevel,
                                              Source__c=sourceClass,
                                              Source_Function__c=sourceFunction,
                                              Message__c=logMessage,            		
                                              Integration_Payload__c=payLoad,
                                              Timer__c=timeTaken
                                          );
                                          if(ex != null)        
                                              log.Stack_Trace__c=ex.getStackTraceString();
                                          logMessage(log);
                                      }    
        /*------------------------------------------------------------ 
    Author: Stefano Pramparo 
    Company: Sky DE
    Description: Function to add the error message in the lit; data is committed invoking flush method
    or when getLimitDmlRows()-1 has been reached
    Inputs: log: object of type Application_Log__c
    Returns: n.a.
    History 
    <Date>	 		<Authors Name>		<Brief Description of Change> 
    31.08.2018		Stefano Pramparo	Created
    ------------------------------------------------------------*/
        public static void logMessage(Application_Log__c log){
            logList.add(log);
            if(logList.size()==Limits.getLimitDmlRows() || Limits.getHeapSize()+DMLHEAP >= Limits.getLimitHeapSize())
                flush();
        }
        /*------------------------------------------------------------ 
    Author: Stefano Pramparo 
    Company: Sky DE
    Description: Function to flush log array, it will trigger an insert
    Inputs: n.a
    Returns: n.a.
    History 
    <Date>	 		<Authors Name>		<Brief Description of Change> 
    31.08.2018		Stefano Pramparo	Created
    ------------------------------------------------------------*/
        public static void flush(){       
            if(Limits.getDMLStatements()<Limits.getLimitDmlStatements()){
                insert logList;
            }else{
                System.debug('Warning Limits exceed, log records discarded');
            }
            logList.clear();
        }
    }