objects/LiveText__Conversation_Header__c.object
<CustomObject>
    <description>LiveMessage Session</description>
    <fields>
        <fullName>LiveText__Originating_Number__c</fullName>
        <label>Recipient</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LiveText__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Offline</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>LiveMessage Session</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>LiveMessage Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LiveMessage Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LiveText__SMS_Text__c.object
<CustomObject>
    <description>SMS Text</description>
    <fields>
        <fullName>LiveText__Conversation_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Conversation Header</label>
        <referenceTo>LiveText__Conversation_Header__c</referenceTo>
        <relationshipLabel>SMS Texts (Conversation Header)</relationshipLabel>
        <relationshipName>SMS_Text</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LiveText__Message__c</fullName>
        <label>Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LiveText__Originating_Number__c</fullName>
        <description>Originating Number</description>
        <label>Originating Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LiveText__Status__c</fullName>
        <description>Status of message delivery</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SMS Text</label>
    <nameField>
        <displayFormat>SMS-{0000}</displayFormat>
        <label>SMS Text Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Texts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ChatScreen_CC_Test.cls
/*------------------------------------------------------------
Author: Pavel Usoltsev
Company: Salesforce
Description: A test class created to get the data displayed in the chat component
Tests executed:
             1 - getConversationData()
             Get active session data
             Make SOQL query, which return result of values.
             Compare received result with expected

History
8/10/18    Pavel Usoltsev    Initial Version.
05.02.2019  Sven Kretschmann    Split class from LiveSessionHeaders_CC_Test, improve assertions of tests
------------------------------------------------------------*/
@IsTest
private class ChatScreen_CC_Test {

    @IsTest
    private static void testGetConversationData() {
        TestDataFactory.setInsertOBjects(true);

        TestDataFactory.setFieldNameValuePairs('LiveText__Status__c', 'New');
        TestDataFactory.setFieldNameValuePairs('LiveText__Originating_Number__c', '2157762154239024');
        LiveText__Conversation_Header__c testLiveText = (LiveText__Conversation_Header__c) TestDataFactory.createSObject('LiveText__Conversation_Header__c');
        TestDataFactory.resetFieldNameValuePairs();

        String response = ChatScreen_CC.getConversationData(testLiveText.Id);
        System.assert(response.length() > 0);
        System.assert(response.contains('"type":"LiveText__Conversation_Header__c"'));
        System.assert(response.contains('"Id":"' + testLiveText.Id + '"'));
        System.assert(response.contains('"LiveText__Originating_Number__c":"2157762154239024"'));
    }

    @IsTest
    private static void testGetSMSData() {
        TestDataFactory.setInsertOBjects(true);

        TestDataFactory.setFieldNameValuePairs('LiveText__Message__c', 'test message');
        TestDataFactory.setFieldNameValuePairs('LiveText__Originating_Number__c', '2157762154239024');
        LiveText__SMS_Text__c testSms = (LiveText__SMS_Text__c) TestDataFactory.createSObject('LiveText__SMS_Text__c');
        TestDataFactory.resetFieldNameValuePairs();

        String response = ChatScreen_CC.getSmsData(testSms.Id);

        System.assert(response.length() > 0);
        System.assert(response.contains('"type":"LiveText__SMS_Text__c"'));
        System.assert(response.contains('"Id":"' + testSms.Id + '"'));
        System.assert(response.contains('"LiveText__Message__c":"test message"'));
    }
}