objects/LiveText__SMS_Message__c.object
<CustomObject>
    <description>An SMS message</description>
    <fields>
        <fullName>LiveText__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account related to this message</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>SMS_Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LiveText__Message_Status__c</fullName>
        <description>Status of the message</description>
        <label>Message Status</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LiveText__Object_Id__c</fullName>
        <description>Id of the object related to this message</description>
        <label>Object Id</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LiveText__To_Phone_Number__c</fullName>
        <description>Phone number to send the message to</description>
        <label>To Phone Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <label>SMS Message</label>
    <nameField>
        <label>SMS Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/QueueMessageClass_Test.cls
/*------------------------------------------------------------------------
Author:      Pavel Usoltsev
Company:     Salesforce
Description: A test class created to validate class QueueMessageClass
             Tests executed:
             testing of execution queueable job for sending live message
             1 - checkIfOptionNumberIsAssigned_Test()
             Create LiveText__SMS_Message__c record with required fields
             Enqueue this message as job
             Compare received result with expected
History
7/2/18    Pavel Usoltsev   Initial Version
----------------------------------------------------------------------------*/
@isTest
private class QueueMessageClass_Test {

    @isTest
    static void execute_Test() {
        TestDataFactory.setInsertOBjects(true);

        //User
        User testUser = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator'][0];

        //Account
        TestDataFactory.setFieldNameValuePairs('RecordTypeId', 'Person Account');
        TestDataFactory.setFieldNameValuePairs('FirstName', 'Cooper');
        TestDataFactory.setFieldNameValuePairs('LastName', 'Hawkes');
        Account testAccount = (Account) TestDataFactory.createSObject('Account');
        TestDataFactory.resetFieldNameValuePairs();

        LiveText__SMS_Message__c testMessage = new LiveText__SMS_Message__c();
        testMessage.LiveText__Account__c = testAccount.Id;
        testMessage.LiveText__Message_Status__c = 'Sent';
        testMessage.LiveText__Object_Id__c = testAccount.Id;
        testMessage.LiveText__To_Phone_Number__c = '+491733404495';

        List<LiveText__SMS_Message__c> testMessages = new List<LiveText__SMS_Message__c>();
        testMessages.add(testMessage);

        Test.startTest();

        System.enqueueJob(new QueueMessageClass(testMessages));

        Test.stopTest();

        List<LiveText__SMS_Message__c> testMessagesList = [SELECT Id FROM LiveText__SMS_Message__c];
        System.assertEquals(1, testMessagesList.size(), 'Results query returned no results');
    }

}