objects/LiveText__Conversation_Header__c.object
<CustomObject>
    <description>LiveMessage Session</description>
    <fields>
        <fullName>LiveText__AcceptedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User who accepted the conversation.</description>
        <label>Accepted By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Text_Session_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LiveText__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Conversation_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LiveText__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Conversation_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LiveText__Originating_Number__c</fullName>
        <label>Recipient</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LiveText__SessionReopenedTime__c</fullName>
        <description>Records the time that a LiveMessage session is re-opened</description>
        <inlineHelpText>Records the time that a text session is re-opened</inlineHelpText>
        <label>SessionReopenedTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LiveText__Support_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Channel</label>
        <referenceTo>LiveText__LiveText_Number__c</referenceTo>
        <relationshipName>Conversation_Headers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LiveMessage Session</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>LiveMessage Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LiveMessage Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LiveText__SMS_Text__c.object
<CustomObject>
    <description>SMS Text</description>
    <fields>
        <fullName>LiveText__Conversation_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Conversation Header</label>
        <referenceTo>LiveText__Conversation_Header__c</referenceTo>
        <relationshipLabel>SMS Texts (Conversation Header)</relationshipLabel>
        <relationshipName>SMS_Text</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LiveText__Message__c</fullName>
        <label>Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LiveText__Originating_Number__c</fullName>
        <description>Originating Number</description>
        <label>Originating Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LiveText__Sent_To_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent to Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LiveText__Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                </value>
                <value>
                    <fullName>LiveText</fullName>
                    <default>true</default>
                    <label>LiveText</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LiveText__Support_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Support Number</label>
        <referenceTo>LiveText__LiveText_Number__c</referenceTo>
        <relationshipLabel>SMS Texts (Support Number)</relationshipLabel>
        <relationshipName>SMS_Text</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SMS Text</label>
    <nameField>
        <displayFormat>SMS-{0000}</displayFormat>
        <label>SMS Text Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Texts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ChatScreen_CC.cls
/*------------------------------------------------------------
Author: Sudipta Karmakar
Company: Salesforce
Description: Controller to get conversation content for supervisors
Inputs:
Test Class:  ChatScreen_CC_Test

History
7/30/18    Sudipta Karmakar    Initial Version.
05.02.2019  Sven Kretschmann    Split class, separate controller for ChatScreen component.
------------------------------------------------------------*/

public with sharing class ChatScreen_CC {
    /*------------------------------------------------------------
    Author:      Sudipta Karmakar
    Company:     Salesforce
    Description: Get data for selected selected session
    Inputs:      SessionId - session Id to find data related to this session
    Returns:     listToSend - serialized data to display for selected session
    Created:     7/30/18
    ------------------------------------------------------------*/
    @AuraEnabled
    public static String getConversationData(String SessionId) {
        List<LiveText__Conversation_Header__c> listToSend = [
            SELECT Id,LiveText__AcceptedBy__r.Name,LiveText__Contact__c,LiveText__Contact__r.Name,CreatedDate,LiveText__SessionReopenedTime__c,LiveText__Originating_Number__c,LiveText__Support_Number__c,LiveText__Account__c, (
                SELECT Id,LiveText__Message__c,LiveText__Sent_To_Customer__c,CreatedBy.Name,CreatedDate
                FROM LiveText__SMS_Text__r
                WHERE LiveText__Source__c != 'Salesforce Linking'
                ORDER BY CreatedDate
            )
            FROM LiveText__Conversation_Header__c
            WHERE Id = :SessionId
        ];

        return JSON.serialize(listToSend);
    }

    /*------------------------------------------------------------
    Author:      Sudipta Karmakar
    Company:     Salesforce
    Description: Get sms content
    Inputs:      smsId - id of sms object to get sms data
    Returns:     string serialized sms content
    ------------------------------------------------------------*/
    @AuraEnabled
    public static String getSmsData(Id smsId) {
        return JSON.serialize([SELECT Id,LiveText__Message__c,LiveText__Sent_To_Customer__c,CreatedBy.Name,CreatedDate FROM LiveText__SMS_Text__c WHERE LiveText__Source__c != 'Salesforce Linking' AND Id = :smsId ORDER BY CreatedDate]);
    }
}